// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieMania.Infrastructure.Data;

#nullable disable

namespace MovieMania.Infrastructure.Migrations
{
    [DbContext(typeof(MovieManiaDbContext))]
    [Migration("20240416175327_FullNamesAdded")]
    partial class FullNamesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Actors.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Actor's identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasComment("Actor's bio");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasComment("Actor's birthdate");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Actor's profile picture url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Actor's name");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasComment("Movie's actor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Jennifer Aniston is an American actress. She rose to international fame for her role as Rachel Green on the television sitcom Friends from 1994 to 2004, which earned her Primetime Emmy, Golden Globe, and Screen Actors Guild awards.",
                            BirthDate = new DateTime(1969, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/16/JenniferAnistonHWoFFeb2012.jpg",
                            Name = "Jeniffer Aniston"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Adam Sandler is an American actor and comedian. Primarily a comedic leading actor in films, his accolades include nominations for three Grammy Awards, five Primetime Emmy Awards, a Golden Globe Award, and a Screen Actors Guild Award. Sandler was awarded the Mark Twain Prize for American Humor.",
                            BirthDate = new DateTime(1966, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Adam_Sandler_at_Berlinale_2024.jpg/800px-Adam_Sandler_at_Berlinale_2024.jpg",
                            Name = "Adam Sandler"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Jonah Hill is an American actor, director and screenwriter. He is known for his comedic roles in films including Superbad, Knocked Up, 21 Jump Street. For his performances in Moneyball and The Wolf of Wall Street, he was nominated for the Academy Award for Best Supporting Actor.",
                            BirthDate = new DateTime(1983, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Jonah_Hill-4939_%28cropped%29_%28cropped%29.jpg/1024px-Jonah_Hill-4939_%28cropped%29_%28cropped%29.jpg",
                            Name = "Jonah Hill"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Leonardo DiCaprio is an American actor and film producer. Known for his work in biographical and period films, he is the recipient of numerous accolades, including an Academy Award, a British Academy Film Award, and three Golden Globe Awards. ",
                            BirthDate = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.usmagazine.com/wp-content/uploads/2024/01/Stars-Who-Are-Continually-Snubbed-by-the-Oscars-Leonardo-DiCaprio-Margot-Robbie-and-More-4.jpg?w=800&h=1421&crop=1&quality=86&strip=all",
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Cillian Murphy is an Irish actor. He made his professional debut in Enda Walsh's 1996 play Disco Pigs, a role he later reprised in the 2001 screen adaptation. He gained greater prominence for his role as Tommy Shelby in the BBC period drama series Peaky Blinders.",
                            BirthDate = new DateTime(1976, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i0.wp.com/www.thewrap.com/wp-content/uploads/2016/04/Cillian-Murphy.jpg?w=618&ssl=1",
                            Name = "Cillian Murphy"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Robert Downey Jr. is an American actor. His career has been characterized by some early success, a period of drug-related problems and run-ins with the law, and a surge in population and commercial success in the 2000s. In 2008, Downey was named by Time magazine as one of the 100 most influential people in the world.",
                            BirthDate = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/9/94/Robert_Downey_Jr_2014_Comic_Con_%28cropped%29.jpg",
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Samuel L. Jackson is an American actor. One of the most widely recognized actors of his generation, the films in which he has appeared have collectively grossed over $27 billion worldwide, making him the highest-grossing actor of all time. In 2022, he received the Academy Honorary Award as a cultural icon whose dynamic work has resonated across genres and generations and audiences worldwide.",
                            BirthDate = new DateTime(1948, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/SamuelLJackson.jpg/800px-SamuelLJackson.jpg",
                            Name = "Samuel L. Jackson"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Brianne Desaulniers, known professionally as Brie Larson, is an American actress. Known for her supporting roles in comedies as a teenager, she has since expanded to leading roles in independent films and blockbusters. She has received various accolades, including an Academy Award, a Golden Globe Award, and a Primetime Emmy Award.",
                            BirthDate = new DateTime(1989, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Captain_Marvel_trailer_at_the_National_Air_and_Space_Museum_4_%28cropped%29.jpg/1024px-Captain_Marvel_trailer_at_the_National_Air_and_Space_Museum_4_%28cropped%29.jpg",
                            Name = "Brie Larson"
                        });
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Carts.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Shopping cart's identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User's identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasComment("User's shopping cart");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Carts.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Cart detail's identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie's identifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of movies in the cart");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int")
                        .HasComment("Shopping cart's identifier");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartDetails");

                    b.HasComment("Detail of user's shopping cart");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.CustomUser.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dea12856-c198-4129-b3f3-b893d8395082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b3d77602-4a4d-4cff-9202-5508d3782881",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Evgeni",
                            LastName = "Tsvetkov",
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@mail.com",
                            NormalizedUserName = "admin@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEG+N8kdmZKgLXw0RXvo/trvW6nvsntgmCc7snHfa+m1JDgZ6JHWDkP8HH61n36g+TQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5281894a-0e7e-41fb-9e79-430cb05ed351",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        },
                        new
                        {
                            Id = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "de399190-56c7-4a45-b546-5321ec2a6279",
                            Email = "guest@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Guest",
                            LastName = "Guestt",
                            LockoutEnabled = false,
                            NormalizedEmail = "guest@mail.com",
                            NormalizedUserName = "guest@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEJXGxDflkiPsWBhtFI7SiUv1e/sX0FSD5hPRoAbFlREfBbskQRyGK/r10iwIOLdEXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03744c2f-c824-4954-a853-7393bbc06aa2",
                            TwoFactorEnabled = false,
                            UserName = "guest@mail.com"
                        });
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Directors.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Director's identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasComment("Director's bio");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasComment("Director's birthday");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Director's profile picture url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Director's name");

                    b.HasKey("Id");

                    b.ToTable("Director");

                    b.HasComment("Movie's director");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Anna Boden is an American film director, cinematographer, editor, andscreenwriter best known as the co-writer of the 2006 film Half Nelson.She is known for her collaborations with fellow filmmaker Ryan Fleck.",
                            BirthDate = new DateTime(1979, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/8f/Anna_Boden.jpg/revision/latest?cb=20190305123354",
                            Name = "Anna Boden"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Judd Apatow is an American director, producer and screenwriter, best known for his work in comedy films. He is the founder of Apatow Productions. Throughout his career, Apatow has received nominations for 11 Primetime Emmy Awards, five Writers Guild of America Awards, two Producers Guild of America Awards, one Golden Globe Award and one Grammy Award.",
                            BirthDate = new DateTime(1967, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/3/3b/2024-03-08_SXSW-2024_comedy-directors_3.jpg",
                            Name = "Judd Apatow"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "After graduating from college, Garelick began his career working as an assistant in Creative Artists Agency's Motion Picture Literary department. He served as the assistant to director Joel Schumacher on Tigerland, Bad Company, and Phone Booth. He was the second unit director on Schumacher’s 2003 movie Veronica Guerin.",
                            BirthDate = new DateTime(1975, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c4/Jeremy_Garelick.png",
                            Name = "Jeremy Garelick"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Martin Scorsese is an American filmmaker. he emerged as one of the major figures of the New Hollywood era. Scorsese has received many accolades, including an Academy Award, four BAFTA Awards, three Emmy Awards, a Grammy Award, three Golden Globe Awards, and two Directors Guild of America Awards. He has been honored with the AFI Life Achievement Award in 1997.",
                            BirthDate = new DateTime(1942, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Martin_Scorsese-68754.jpg/800px-Martin_Scorsese-68754.jpg",
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Christopher Nolan is a British and American filmmaker. Known for his Hollywood blockbusters with complex storytelling, he is considered a leading filmmaker of the 21st century.  His accolades include two Academy Awards and two British Academy Film Awards. Nolan was appointed as a Commander of the Order of the British Empire in 2019, and received a knighthood in 2024 for his contributions to film.",
                            BirthDate = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/9/95/Christopher_Nolan_Cannes_2018.jpg",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Anthony Russo and Joseph Russo collectively known as the Russo brothers, are American directors, producers, and screenwriters. They direct most of their work together. They are best known for directing four films in the Marvel Cinematic Universe: Captain America: The Winter Soldier, Captain America: Civil War, Avengers: Infinity War, and Avengers: Endgame.",
                            BirthDate = new DateTime(1970, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://imageio.forbes.com/specials-images/imageserve/62ca4312f62dcb9b9e34a6e9/Russo-Brothers---Exterior-horizontal/960x0.jpg?format=jpg&width=1440",
                            Name = "Anthony Russo"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Dennis Dugan is an American film director, actor, and comedian. He is known for directing the films Problem Child, Brain Donors, Beverly Hills Ninja and National Security, and his partnership with comedic actor Adam Sandler, for whom he directed the films Happy Gilmore, Big Daddy, The Benchwarmers, I Now Pronounce You Chuck & Larry etc.",
                            BirthDate = new DateTime(1943, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.hobbydb.com/processed_uploads/subject_photo/subject_photo/image/49245/1553650458-4334-5610/Dennis_20Dugan_large.jpg",
                            Name = "Dennis Dugan"
                        });
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Mappings.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie's identifier");

                    b.Property<int>("ActorId")
                        .HasColumnType("int")
                        .HasComment("Actor's identifier");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MoviesActors");

                    b.HasComment("Movie and actor mapping");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 8
                        });
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Movies.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Genre's identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasComment("Genre's name");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasComment("Movie's genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 7,
                            Name = "History"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Romance"
                        });
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Movies.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Movie's identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Movie's description");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int")
                        .HasComment("Director's identifier");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("Movie's genre identifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Movie's image url");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price for single movie");

                    b.Property<int>("ReleaseDate")
                        .HasMaxLength(2024)
                        .HasColumnType("int")
                        .HasComment("Movie's release date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Movie's title");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasComment("Movie to buy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "On a weekend trip to Hawaii, a plastic surgeon convinces his loyal assistant to pose as his soon-to-be-divorced wife in order to cover up a careless lie he told to his much-younger girlfriend.",
                            DirectorId = 7,
                            GenreId = 3,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/en/b/b8/Just_Go_with_It_Poster.jpg",
                            Price = 29.99m,
                            ReleaseDate = 2011,
                            Title = "Just Go with It"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
                            DirectorId = 4,
                            GenreId = 6,
                            ImageURL = "https://moviesfilmsandflix.files.wordpress.com/2013/12/wolf-of-wall-street.jpg",
                            Price = 35.99m,
                            ReleaseDate = 2013,
                            Title = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Full-time detectives Nick and Audrey are struggling to get their private eye agency off the ground. They find themselves at the center of international abduction when their friend Maharaja is kidnapped at his own lavish wedding.",
                            DirectorId = 3,
                            GenreId = 3,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/en/7/71/Murder_Mystery_2_poster.png",
                            Price = 59.99m,
                            ReleaseDate = 2023,
                            Title = "Murder Mystery 2"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
                            DirectorId = 5,
                            GenreId = 1,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
                            Price = 25.99m,
                            ReleaseDate = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 5,
                            Description = "When seasoned comedian George Simmons learns of his terminal, inoperable health condition, his desire to form a genuine friendship causes him to take a relatively green performer under his wing as his opening act.",
                            DirectorId = 2,
                            GenreId = 3,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/en/2/26/PosterFunnyPeople.jpg",
                            Price = 19.99m,
                            ReleaseDate = 2009,
                            Title = "Funny People"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
                            DirectorId = 1,
                            GenreId = 2,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/en/4/4e/Captain_Marvel_%28film%29_poster.jpg",
                            Price = 49.99m,
                            ReleaseDate = 2019,
                            Title = "Captain Marvel"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
                            DirectorId = 5,
                            GenreId = 4,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg",
                            Price = 69.99m,
                            ReleaseDate = 2023,
                            Title = "Oppenheimer"
                        },
                        new
                        {
                            Id = 8,
                            Description = "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
                            DirectorId = 6,
                            GenreId = 1,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
                            Price = 65.99m,
                            ReleaseDate = 2019,
                            Title = "Avengers: Endgame"
                        });
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order's identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasComment("The date of order");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int")
                        .HasComment("Order status identifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User's identifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasComment("User's order");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Orders.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order detail identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie's identifier");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("Order's identifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of ordered movies");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price for single movie");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasComment("Details of user's orders");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Orders.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order status identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Order status name");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasComment("Status identifier");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasComment("Status of user's order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.CustomUser.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.CustomUser.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieMania.Infrastructure.Data.Models.CustomUser.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.CustomUser.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Carts.Cart", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.CustomUser.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Carts.CartDetail", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.Movies.Movie", "Movie")
                        .WithMany("CartDetails")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieMania.Infrastructure.Data.Models.Carts.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Mappings.MovieActor", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.Actors.Actor", "Actor")
                        .WithMany("MoviesActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieMania.Infrastructure.Data.Models.Movies.Movie", "Movie")
                        .WithMany("MoviesActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Movies.Movie", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.Directors.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieMania.Infrastructure.Data.Models.Movies.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Orders.Order", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.Orders.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieMania.Infrastructure.Data.Models.CustomUser.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Orders.OrderDetail", b =>
                {
                    b.HasOne("MovieMania.Infrastructure.Data.Models.Movies.Movie", "Movie")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieMania.Infrastructure.Data.Models.Orders.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Actors.Actor", b =>
                {
                    b.Navigation("MoviesActors");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Carts.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Directors.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Movies.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Movies.Movie", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("MoviesActors");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Orders.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MovieMania.Infrastructure.Data.Models.Orders.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
